default: true
line-length: false
#  line_length: 88
#  tables: false
no-trailing-punctuation: true
heading-style:
  style: atx
no-missing-space-atx: true
single-title: false
fenced-code-language: true
code-block-style:
  style: fenced
no-duplicate-heading:
  siblings_only: true
# todo reenable this
no-inline-html: false
first-line-heading: false