# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenEM
email: spencer.bliven@psi.ch
description: >- # this means to ignore newlines until "baseurl:"
  The Swiss Open EM Data Network
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  SwissOpenEM

# Build settings
remote_theme: hydecorp/hydejack@v9.1.6

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md

plugins:
  - jekyll-include-cache
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Hydejack config: https://hydejack.com/docs/config/

author:
  name:  Spencer Bliven
  email: spencer.bliven@psi.ch
  social:
    github:  SwissOpenEM
    email: spencer.bliven@psi.ch

logo: /assets/img/logo-512x512.png
accent_image: /assets/img/orientation-map.jpg
#accent_color: rgb(79,177,186)
sidebar_footer: "[Image Credits](/news/2023/06/14/logo.html)"

favicon: /assets/icons/favicon.ico
apple_touch_icon: /assets/icons/apple-touch-icon.png

menu:
  - title: Overview
    url:   /overview/
  - title: Members
    url:   /members/
  - title: Jobs
    url:   /jobs/