# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenEM
email: spencer.bliven@psi.ch
description: >- # this means to ignore newlines until "baseurl:"
  The Swiss Open EM Data Network
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
title-img: "/assets/img/logo-wide-1024x317.png"

sass:
  sass_dir: _sass
  style: compressed

# Build settings
remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-remote-theme

###############################################
# --- List of links in the navigation bar --- #
###############################################

# Add a search button to the navbar
post_search: true

navbar-links:
  News: "news"
  The Project:
    - About: "about"
    - Deliverables: "deliverables"
    - Roadmap: "roadmap"
    - Software: "software"
    - References: "references"
  Team: "team"
  Outreach: "outreach"
  Documentation: "documentation"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
site-css:
  - "/assets/css/customOpenEM.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

  #####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# You can change the order that they show up on the page by changing the order here.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "spencer.bliven@psi.ch"
  rss: false # remove this line if you don't want to show an RSS link at the bottom
  # facebook: deanattali
  github: SwissOpenEM
  # twitter: 
  # patreon: 
  # youtube: 
#  medium: yourname
#  reddit: yourname
#  linkedin: 
#  xing: yourname
#  stackoverflow: "
#  snapchat: 
#  instagram: 
#  spotify: yourname
#  telephone: +14159998888
#  steam: 
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  bluesky: yourname
#  ORCID: your ORCID ID
#  google-scholar: your google scholar
#  discord: "invite_code" or "users/userid" or "invite/invite_code"
#  kaggle: yourname
#  hackerrank: yourname
#  gitlab: yourname

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
