services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: swissopenem:latest
    ports:
      - "4000:4000"
    volumes:
      - ".:/src"
    # As of alpine 3.20, jekyll doesn't run on aarm64
    platform: linux/amd64
